---
- name: Display current OS version
  ansible.builtin.debug:
    msg: Currently running {{ ansible_net_version }}

- name: Platform-specific upgrade
  ansible.builtin.include_tasks: "{{ ansible_network_os.split('.')[2] }}.yml"
